import { RouteWithDetails } from '@/types'

export const mockRoutes: RouteWithDetails[] = [
  {
    id: '1',
    user_id: 'user-1',
    title: 'Pacific Coast Highway: Big Sur Edition',
    description: 'Experience one of the most scenic coastal drives in the world. This route takes you through the dramatic cliffs of Big Sur, with countless viewpoints overlooking the Pacific Ocean.',
    difficulty: 'moderate',
    distance_km: 145,
    duration_minutes: 240,
    elevation_gain_m: 1200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-121.9018, 36.6002],
        [-121.8742, 36.4502],
        [-121.6805, 36.2342],
      ],
    },
    region: 'California, USA',
    category: 'coastal',
    scenic_score: 9.8,
    road_quality_score: 8.5,
    fun_factor_score: 9.2,
    featured: true,
    published: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    rating_count: 247,
    average_rating: 9.2,
    stops: [
      {
        id: 'stop-1',
        route_id: '1',
        name: 'Bixby Bridge',
        description: 'Iconic bridge with stunning ocean views',
        type: 'viewpoint',
        latitude: 36.3717,
        longitude: -121.9021,
        order_index: 1,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'stop-2',
        route_id: '1',
        name: 'Nepenthe Restaurant',
        description: 'Famous restaurant with panoramic views',
        type: 'restaurant',
        latitude: 36.2458,
        longitude: -121.8105,
        order_index: 2,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'stop-3',
        route_id: '1',
        name: 'McWay Falls',
        description: 'Beautiful waterfall flowing directly into the ocean',
        type: 'viewpoint',
        latitude: 36.1597,
        longitude: -121.6693,
        order_index: 3,
        created_at: '2024-01-15T10:00:00Z',
      },
    ],
  },
  {
    id: '2',
    user_id: 'user-2',
    title: 'Stelvio Pass: Alpine Adventure',
    description: 'Conquer one of the highest paved mountain passes in the Eastern Alps. Famous for its 48 hairpin turns and breathtaking alpine scenery.',
    difficulty: 'expert',
    distance_km: 78,
    duration_minutes: 180,
    elevation_gain_m: 1871,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [10.4520, 46.5281],
        [10.4520, 46.5281],
      ],
    },
    region: 'Italian Alps',
    category: 'mountain',
    scenic_score: 10,
    road_quality_score: 8.0,
    fun_factor_score: 9.8,
    featured: true,
    published: true,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    rating_count: 189,
    average_rating: 9.6,
  },
  {
    id: '3',
    user_id: 'user-1',
    title: 'Blue Ridge Parkway: Autumn Colors',
    description: 'A leisurely ride through the Appalachian Highlands. Best experienced in fall when the mountains explode with color.',
    difficulty: 'easy',
    distance_km: 192,
    duration_minutes: 300,
    elevation_gain_m: 890,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-82.5515, 35.5951],
        [-79.0753, 36.5782],
      ],
    },
    region: 'North Carolina, USA',
    category: 'scenic',
    scenic_score: 9.5,
    road_quality_score: 9.0,
    fun_factor_score: 8.5,
    featured: true,
    published: true,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
    rating_count: 156,
    average_rating: 9.1,
  },
  {
    id: '4',
    user_id: 'user-3',
    title: 'Great Ocean Road: Twelve Apostles',
    description: 'Australia\'s most famous coastal drive featuring limestone stacks rising from the Southern Ocean.',
    difficulty: 'easy',
    distance_km: 243,
    duration_minutes: 360,
    elevation_gain_m: 450,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [144.3540, -38.3843],
        [142.9845, -38.6649],
      ],
    },
    region: 'Victoria, Australia',
    category: 'coastal',
    scenic_score: 9.7,
    road_quality_score: 9.5,
    fun_factor_score: 8.8,
    featured: false,
    published: true,
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-01-05T10:00:00Z',
    rating_count: 203,
    average_rating: 9.3,
  },
  {
    id: '5',
    user_id: 'user-2',
    title: 'Transfăgărășan Highway: Romania\'s Best',
    description: 'The most dramatic road in Romania, crossing the Carpathian Mountains with stunning switchbacks and tunnels.',
    difficulty: 'challenging',
    distance_km: 152,
    duration_minutes: 240,
    elevation_gain_m: 1633,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [24.6179, 45.3510],
        [24.6179, 45.6014],
      ],
    },
    region: 'Carpathian Mountains, Romania',
    category: 'mountain',
    scenic_score: 9.6,
    road_quality_score: 7.5,
    fun_factor_score: 9.4,
    featured: false,
    published: true,
    created_at: '2024-01-03T10:00:00Z',
    updated_at: '2024-01-03T10:00:00Z',
    rating_count: 134,
    average_rating: 9.0,
  },
  {
    id: '6',
    user_id: 'user-3',
    title: 'North Coast 500: Scottish Highlands',
    description: 'Scotland\'s answer to Route 66. A circular route through the stunning landscapes of the Scottish Highlands.',
    difficulty: 'moderate',
    distance_km: 830,
    duration_minutes: 1440,
    elevation_gain_m: 3200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-4.4244, 57.4778],
        [-5.8342, 58.6379],
      ],
    },
    region: 'Scottish Highlands, Scotland',
    category: 'adventure',
    scenic_score: 9.4,
    road_quality_score: 8.5,
    fun_factor_score: 9.0,
    featured: false,
    published: true,
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-01-01T10:00:00Z',
    rating_count: 98,
    average_rating: 8.9,
  },
]
