import { RouteWithDetails } from '@/types'

export const mockRoutes: RouteWithDetails[] = [
  {
    id: '1',
    user_id: 'user-1',
    title: 'Pacific Coast Highway: Big Sur Edition',
    description: 'Experience one of the most scenic coastal drives in the world. This route takes you through the dramatic cliffs of Big Sur, with countless viewpoints overlooking the Pacific Ocean.',
    difficulty: 'moderate',
    distance_km: 145,
    duration_minutes: 240,
    elevation_gain_m: 1200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-121.9018, 36.6002],
        [-121.8742, 36.4502],
        [-121.6805, 36.2342],
      ],
    },
    region: 'California, USA',
    category: 'coastal',
    scenic_score: 9.8,
    road_quality_score: 8.5,
    fun_factor_score: 9.2,
    featured: true,
    published: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    rating_count: 247,
    average_rating: 9.2,
    stops: [
      {
        id: 'stop-1',
        route_id: '1',
        name: 'Bixby Bridge',
        description: 'Iconic bridge with stunning ocean views',
        type: 'viewpoint',
        latitude: 36.3717,
        longitude: -121.9021,
        order_index: 1,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'stop-2',
        route_id: '1',
        name: 'Nepenthe Restaurant',
        description: 'Famous restaurant with panoramic views',
        type: 'restaurant',
        latitude: 36.2458,
        longitude: -121.8105,
        order_index: 2,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'stop-3',
        route_id: '1',
        name: 'McWay Falls',
        description: 'Beautiful waterfall flowing directly into the ocean',
        type: 'viewpoint',
        latitude: 36.1597,
        longitude: -121.6693,
        order_index: 3,
        created_at: '2024-01-15T10:00:00Z',
      },
    ],
  },
  {
    id: '2',
    user_id: 'user-2',
    title: 'Stelvio Pass: Alpine Adventure',
    description: 'Conquer one of the highest paved mountain passes in the Eastern Alps. Famous for its 48 hairpin turns and breathtaking alpine scenery.',
    difficulty: 'expert',
    distance_km: 78,
    duration_minutes: 180,
    elevation_gain_m: 1871,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [10.4520, 46.5281],
        [10.4520, 46.5281],
      ],
    },
    region: 'Italian Alps',
    category: 'mountain',
    scenic_score: 10,
    road_quality_score: 8.0,
    fun_factor_score: 9.8,
    featured: true,
    published: true,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    rating_count: 189,
    average_rating: 9.6,
  },
  {
    id: '3',
    user_id: 'user-1',
    title: 'Blue Ridge Parkway: Autumn Colors',
    description: 'A leisurely ride through the Appalachian Highlands. Best experienced in fall when the mountains explode with color.',
    difficulty: 'easy',
    distance_km: 192,
    duration_minutes: 300,
    elevation_gain_m: 890,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-82.5515, 35.5951],
        [-79.0753, 36.5782],
      ],
    },
    region: 'North Carolina, USA',
    category: 'scenic',
    scenic_score: 9.5,
    road_quality_score: 9.0,
    fun_factor_score: 8.5,
    featured: true,
    published: true,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
    rating_count: 156,
    average_rating: 9.1,
  },
  {
    id: '4',
    user_id: 'user-3',
    title: 'Great Ocean Road: Twelve Apostles',
    description: 'Australia\'s most famous coastal drive featuring limestone stacks rising from the Southern Ocean.',
    difficulty: 'easy',
    distance_km: 243,
    duration_minutes: 360,
    elevation_gain_m: 450,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [144.3540, -38.3843],
        [142.9845, -38.6649],
      ],
    },
    region: 'Victoria, Australia',
    category: 'coastal',
    scenic_score: 9.7,
    road_quality_score: 9.5,
    fun_factor_score: 8.8,
    featured: false,
    published: true,
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-01-05T10:00:00Z',
    rating_count: 203,
    average_rating: 9.3,
  },
  {
    id: '5',
    user_id: 'user-2',
    title: 'Transfăgărășan Highway: Romania\'s Best',
    description: 'The most dramatic road in Romania, crossing the Carpathian Mountains with stunning switchbacks and tunnels.',
    difficulty: 'challenging',
    distance_km: 152,
    duration_minutes: 240,
    elevation_gain_m: 1633,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [24.6179, 45.3510],
        [24.6179, 45.6014],
      ],
    },
    region: 'Carpathian Mountains, Romania',
    category: 'mountain',
    scenic_score: 9.6,
    road_quality_score: 7.5,
    fun_factor_score: 9.4,
    featured: false,
    published: true,
    created_at: '2024-01-03T10:00:00Z',
    updated_at: '2024-01-03T10:00:00Z',
    rating_count: 134,
    average_rating: 9.0,
  },
  {
    id: '6',
    user_id: 'user-3',
    title: 'North Coast 500: Scottish Highlands',
    description: 'Scotland\'s answer to Route 66. A circular route through the stunning landscapes of the Scottish Highlands.',
    difficulty: 'moderate',
    distance_km: 830,
    duration_minutes: 1440,
    elevation_gain_m: 3200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-4.4244, 57.4778],
        [-5.8342, 58.6379],
      ],
    },
    region: 'Scottish Highlands, Scotland',
    category: 'adventure',
    scenic_score: 9.4,
    road_quality_score: 8.5,
    fun_factor_score: 9.0,
    featured: false,
    published: true,
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-01-01T10:00:00Z',
    rating_count: 98,
    average_rating: 8.9,
  },
  {
    id: '7',
    user_id: 'user-1',
    title: 'N222: Douro Valley Wine Route',
    description: 'Considerada uma das melhores estradas do mundo pela Avis. Serpenteando pelo Vale do Douro entre vinhedos em socalcos e vistas deslumbrantes sobre o rio.',
    difficulty: 'moderate',
    distance_km: 27,
    duration_minutes: 45,
    elevation_gain_m: 380,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-7.5931, 41.1095],
        [-7.7850, 41.1579],
      ],
    },
    region: 'Peso da Régua - Pinhão, Portugal',
    category: 'scenic',
    scenic_score: 9.7,
    road_quality_score: 8.8,
    fun_factor_score: 9.3,
    featured: true,
    published: true,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
    rating_count: 312,
    average_rating: 9.5,
    stops: [
      {
        id: 'stop-7-1',
        route_id: '7',
        name: 'Miradouro de São Leonardo da Galafura',
        description: 'Vista panorâmica sobre o Vale do Douro',
        type: 'viewpoint',
        latitude: 41.1234,
        longitude: -7.6543,
        order_index: 1,
        created_at: '2024-02-15T10:00:00Z',
      },
      {
        id: 'stop-7-2',
        route_id: '7',
        name: 'Quinta do Bomfim',
        description: 'Prova de vinhos do Porto',
        type: 'restaurant',
        latitude: 41.1579,
        longitude: -7.5345,
        order_index: 2,
        created_at: '2024-02-15T10:00:00Z',
      },
    ],
  },
  {
    id: '8',
    user_id: 'user-2',
    title: 'EN2: A Maior Rota de Portugal',
    description: 'Percorra Portugal de norte a sul pela mítica EN2. De Chaves ao Algarve, 739km de paisagens diversas, aldeias tradicionais e autêntica experiência portuguesa.',
    difficulty: 'challenging',
    distance_km: 739,
    duration_minutes: 900,
    elevation_gain_m: 6200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-7.4694, 41.7406],
        [-8.0155, 37.0179],
      ],
    },
    region: 'Chaves - Faro, Portugal',
    category: 'adventure',
    scenic_score: 9.2,
    road_quality_score: 8.0,
    fun_factor_score: 9.0,
    featured: true,
    published: true,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-02-10T10:00:00Z',
    rating_count: 187,
    average_rating: 9.1,
  },
  {
    id: '9',
    user_id: 'user-3',
    title: 'Serra da Estrela: Teto de Portugal',
    description: 'Conquiste a montanha mais alta de Portugal Continental. Curvas sinuosas, paisagens alpinas e no inverno, até neve. A N339 é pura emoção.',
    difficulty: 'expert',
    distance_km: 45,
    duration_minutes: 90,
    elevation_gain_m: 1200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-7.6126, 40.3456],
        [-7.5515, 40.3234],
      ],
    },
    region: 'Serra da Estrela, Portugal',
    category: 'mountain',
    scenic_score: 9.8,
    road_quality_score: 8.5,
    fun_factor_score: 9.7,
    featured: false,
    published: true,
    created_at: '2024-02-08T10:00:00Z',
    updated_at: '2024-02-08T10:00:00Z',
    rating_count: 156,
    average_rating: 9.4,
  },
  {
    id: '10',
    user_id: 'user-1',
    title: 'Rota Vicentina: Costa Alentejana',
    description: 'Praias selvagens, falésias dramáticas e aldeias pitorescas. A costa alentejana preservada oferece uma das rotas costeiras mais bonitas da Europa.',
    difficulty: 'easy',
    distance_km: 120,
    duration_minutes: 180,
    elevation_gain_m: 450,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-8.7851, 37.0179],
        [-8.8648, 37.8517],
      ],
    },
    region: 'Alentejo, Portugal',
    category: 'coastal',
    scenic_score: 9.5,
    road_quality_score: 8.7,
    fun_factor_score: 8.8,
    featured: false,
    published: true,
    created_at: '2024-02-05T10:00:00Z',
    updated_at: '2024-02-05T10:00:00Z',
    rating_count: 143,
    average_rating: 9.2,
  },
  {
    id: '11',
    user_id: 'user-2',
    title: 'Parque Natural Peneda-Gerês',
    description: 'O único parque nacional de Portugal. Montanhas verdejantes, aldeias de xisto, cascatas e miradouros de cortar a respiração. A N308 é espetacular.',
    difficulty: 'moderate',
    distance_km: 85,
    duration_minutes: 150,
    elevation_gain_m: 920,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-8.1582, 41.7234],
        [-8.0932, 41.8654],
      ],
    },
    region: 'Gerês, Portugal',
    category: 'mountain',
    scenic_score: 9.6,
    road_quality_score: 7.8,
    fun_factor_score: 9.1,
    featured: false,
    published: true,
    created_at: '2024-02-03T10:00:00Z',
    updated_at: '2024-02-03T10:00:00Z',
    rating_count: 201,
    average_rating: 9.3,
  },
  {
    id: '12',
    user_id: 'user-3',
    title: 'Sintra-Cascais: Palaces & Ocean',
    description: 'De palácios encantados às praias do Atlântico. Cabo da Roca (ponto mais ocidental da Europa), Guincho e a estrada costeira N247 são imperdíveis.',
    difficulty: 'easy',
    distance_km: 35,
    duration_minutes: 75,
    elevation_gain_m: 380,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-9.3900, 38.7969],
        [-9.4214, 38.6966],
      ],
    },
    region: 'Sintra - Cascais, Portugal',
    category: 'coastal',
    scenic_score: 9.4,
    road_quality_score: 9.2,
    fun_factor_score: 8.7,
    featured: false,
    published: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
    rating_count: 278,
    average_rating: 9.0,
  },
  {
    id: '13',
    user_id: 'user-1',
    title: 'Monsanto: Aldeia Histórica',
    description: 'Visite a "aldeia mais portuguesa de Portugal". Casas entre rochedos gigantes, castelo medieval e vistas sobre a planície beirã. Uma viagem no tempo.',
    difficulty: 'easy',
    distance_km: 65,
    duration_minutes: 120,
    elevation_gain_m: 340,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-7.1138, 40.2797],
        [-7.1093, 40.0393],
      ],
    },
    region: 'Beira Baixa, Portugal',
    category: 'weekend',
    scenic_score: 8.9,
    road_quality_score: 8.3,
    fun_factor_score: 8.5,
    featured: false,
    published: true,
    created_at: '2024-01-28T10:00:00Z',
    updated_at: '2024-01-28T10:00:00Z',
    rating_count: 89,
    average_rating: 8.8,
  },
  {
    id: '14',
    user_id: 'user-1',
    title: 'Ruta de los Pirineos',
    description: 'Uma das rotas mais espetaculares da Europa. Atravessa os Pirinéus de leste a oeste, passando por curvas impressionantes, desfiladeiros e picos nevados com vistas deslumbrantes.',
    difficulty: 'expert',
    distance_km: 420,
    duration_minutes: 540,
    elevation_gain_m: 4200,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-0.7656, 42.6553],
        [0.8801, 42.5833],
        [1.7321, 42.5063],
      ],
    },
    region: 'Pirinéus, Espanha',
    category: 'mountain',
    scenic_score: 9.7,
    road_quality_score: 8.8,
    fun_factor_score: 9.6,
    featured: true,
    published: true,
    created_at: '2024-01-29T10:00:00Z',
    updated_at: '2024-01-29T10:00:00Z',
    rating_count: 298,
    average_rating: 9.6,
    stops: [
      {
        id: 'stop-14-1',
        route_id: '14',
        name: 'Pico del Midi',
        description: 'Mirante com vista 360° dos Pirinéus',
        type: 'viewpoint',
        latitude: 42.9367,
        longitude: 0.1407,
        order_index: 1,
        created_at: '2024-01-29T10:00:00Z',
      },
      {
        id: 'stop-14-2',
        route_id: '14',
        name: 'Refugio de Respomuso',
        description: 'Refúgio tradicional com gastronomia local',
        type: 'restaurant',
        latitude: 42.8012,
        longitude: -0.3425,
        order_index: 2,
        created_at: '2024-01-29T10:00:00Z',
      },
    ],
  },
  {
    id: '15',
    user_id: 'user-2',
    title: 'Picos de Europa',
    description: 'Rota circular pelos impressionantes Picos de Europa. Estradas sinuosas através de desfiladeiros calcários, lagos glaciares e vilas tradicionais asturianas.',
    difficulty: 'moderate',
    distance_km: 180,
    duration_minutes: 300,
    elevation_gain_m: 2100,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-4.9847, 43.2051],
        [-4.8167, 43.1843],
        [-4.7234, 43.2456],
      ],
    },
    region: 'Astúrias, Espanha',
    category: 'mountain',
    scenic_score: 9.4,
    road_quality_score: 8.4,
    fun_factor_score: 9.1,
    featured: true,
    published: true,
    created_at: '2024-01-30T10:00:00Z',
    updated_at: '2024-01-30T10:00:00Z',
    rating_count: 215,
    average_rating: 9.3,
  },
  {
    id: '16',
    user_id: 'user-3',
    title: 'Costa Brava - Girona',
    description: 'Rota costeira espetacular pela Costa Brava. Estradas sinuosas com vistas para o Mediterrâneo, praias escondidas, vilarejos medievais e a impressionante Cap de Creus.',
    difficulty: 'easy',
    distance_km: 95,
    duration_minutes: 180,
    elevation_gain_m: 650,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [2.8232, 41.9794],
        [3.1588, 42.1195],
        [3.3194, 42.3265],
      ],
    },
    region: 'Catalunha, Espanha',
    category: 'coastal',
    scenic_score: 9.1,
    road_quality_score: 8.9,
    fun_factor_score: 8.7,
    featured: false,
    published: true,
    created_at: '2024-01-31T10:00:00Z',
    updated_at: '2024-01-31T10:00:00Z',
    rating_count: 267,
    average_rating: 9.0,
    stops: [
      {
        id: 'stop-16-1',
        route_id: '16',
        name: 'Cadaqués',
        description: 'Vila branca de pescadores, favorita de Salvador Dalí',
        type: 'landmark',
        latitude: 42.2889,
        longitude: 3.2751,
        order_index: 1,
        created_at: '2024-01-31T10:00:00Z',
      },
    ],
  },
  {
    id: '17',
    user_id: 'user-2',
    title: 'Sierra de Gredos - Ávila',
    description: 'Travessia pela majestosa Sierra de Gredos. Estrada de montanha com curvas técnicas, atravessando bosques de pinheiros, lagoas glaciares e picos graníticos.',
    difficulty: 'moderate',
    distance_km: 125,
    duration_minutes: 240,
    elevation_gain_m: 1800,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-4.9516, 40.2981],
        [-5.2267, 40.2456],
        [-5.3945, 40.2896],
      ],
    },
    region: 'Castilla y León, Espanha',
    category: 'mountain',
    scenic_score: 8.9,
    road_quality_score: 8.2,
    fun_factor_score: 8.8,
    featured: false,
    published: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
    rating_count: 142,
    average_rating: 8.9,
  },
  {
    id: '18',
    user_id: 'user-1',
    title: 'Ruta de las Alpujarras',
    description: 'Viagem pelas Alpujarras de Granada, ao sul da Sierra Nevada. Pueblos blancos suspensos nas montanhas, vales verdejantes e curvas infinitas com vistas para o Mediterrâneo.',
    difficulty: 'easy',
    distance_km: 110,
    duration_minutes: 210,
    elevation_gain_m: 980,
    polyline_coordinates: {
      type: 'LineString',
      coordinates: [
        [-3.4603, 36.9567],
        [-3.3587, 36.9123],
        [-3.1825, 36.8456],
      ],
    },
    region: 'Andaluzia, Espanha',
    category: 'scenic',
    scenic_score: 9.2,
    road_quality_score: 8.6,
    fun_factor_score: 8.9,
    featured: false,
    published: true,
    created_at: '2024-02-02T10:00:00Z',
    updated_at: '2024-02-02T10:00:00Z',
    rating_count: 178,
    average_rating: 9.1,
    stops: [
      {
        id: 'stop-18-1',
        route_id: '18',
        name: 'Pampaneira',
        description: 'Pueblo blanco típico das Alpujarras',
        type: 'landmark',
        latitude: 36.9456,
        longitude: -3.3567,
        order_index: 1,
        created_at: '2024-02-02T10:00:00Z',
      },
      {
        id: 'stop-18-2',
        route_id: '18',
        name: 'Capileira',
        description: 'A vila mais alta das Alpujarras com vistas incríveis',
        type: 'viewpoint',
        latitude: 36.9634,
        longitude: -3.3542,
        order_index: 2,
        created_at: '2024-02-02T10:00:00Z',
      },
    ],
  },
]

